FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
RUN rm -rf /usr/share/nginx/html/*

# Copy custom Nginx config
COPY app/frontend/nginx.conf /etc/nginx/conf.d/default.conf

# Copy all directories
COPY app/frontend/static/auth/css /usr/share/nginx/html/css
COPY app/frontend/static/auth/js/animation /usr/share/nginx/html/js
COPY app/frontend/static/auth/js /usr/share/nginx/html/js

COPY app/frontend/static/helpers/css /usr/share/nginx/html/css
COPY app/frontend/static/helpers/js /usr/share/nginx/html/js

COPY app/frontend/static/main_page/css /usr/share/nginx/html/css
COPY app/frontend/static/main_page/js/animation /usr/share/nginx/html/js
COPY app/frontend/static/main_page/js /usr/share/nginx/html/js

COPY app/frontend/static/profile/css /usr/share/nginx/html/css
COPY app/frontend/static/profile/js/animation /usr/share/nginx/html/js
COPY app/frontend/static/profile/js /usr/share/nginx/html/js

COPY app/frontend/templates/auth /usr/share/nginx/html
COPY app/frontend/templates/main_page /usr/share/nginx/html

RUN chmod -R 755 /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]