"""connection added users and refresh_tokens

Revision ID: 3bab0e3438d6
Revises: e8f87057e556
Create Date: 2025-03-26 18:04:35.914534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bab0e3438d6'
down_revision: Union[str, None] = 'e8f87057e556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'refresh_tokens', ['token'])
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_column('refresh_tokens', 'user_id')
    # ### end Alembic commands ###
